# Generated by Django 5.2.17 on 2026-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('project', '项目'), ('article', '文章'), ('note', '随记'), ('standard', '规范'), ('resource', '资源'), ('tool', '工具')], db_index=True, max_length=16, verbose_name='内容类型')),
                ('object_id', models.CharField(max_length=64, verbose_name='对象标识')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('search_text', models.TextField(blank=True, verbose_name='检索文本')),
                ('url', models.CharField(max_length=500, verbose_name='站内地址')),
                ('access_level', models.CharField(db_index=True, default='L0', max_length=2, verbose_name='最低等级')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='来源更新时间')),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='索引时间')),
            ],
            options={
                'verbose_name': '搜索记录',
                'verbose_name_plural': '搜索记录',
                'ordering': ('kind', 'title'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'object_id'), name='unique_search_document_source')],
            },
        ),
    ]
