# Generated by Django 5.2.17 on 2026-08-16 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_seed_studio_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('bulk_publish', '批量发布'), ('bulk_unpublish', '批量取消发布'), ('move_to_trash', '移入回收站'), ('restore_from_trash', '移出回收站'), ('permanent_delete', '永久删除')], db_index=True, max_length=32, verbose_name='动作')),
                ('object_type', models.CharField(max_length=40, verbose_name='对象类型')),
                ('object_id', models.CharField(max_length=64, verbose_name='对象标识')),
                ('object_label', models.CharField(max_length=240, verbose_name='对象名称')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='操作原因')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='非敏感附加信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studio_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '后台审计记录',
                'verbose_name_plural': '后台审计记录',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['object_type', 'object_id', '-created_at'], name='studio_audit_object_idx')],
            },
        ),
    ]
