# Generated by Django 5.2.17 on 2026-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('bulk_publish', '批量发布'), ('bulk_unpublish', '批量取消发布'), ('move_to_trash', '移入回收站'), ('restore_from_trash', '移出回收站'), ('permanent_delete', '永久删除'), ('manual_save', '手工保存'), ('publish', '发布内容')], db_index=True, max_length=32, verbose_name='动作'),
        ),
    ]
