# Generated by Django 5.2.17 on 2026-08-15 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邮箱验证时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_level',
            field=models.CharField(choices=[('L0', '待验证'), ('L1', '普通会员'), ('L2', '高级会员'), ('L3', '站长')], db_index=True, default='L0', max_length=2, verbose_name='会员等级'),
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('deactivate', '停用账号'), ('export', '导出数据'), ('delete', '删除账号')], max_length=16, verbose_name='申请类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=12, verbose_name='状态')),
                ('note', models.TextField(blank=True, max_length=1000, verbose_name='用户说明')),
                ('resolution_note', models.TextField(blank=True, max_length=1000, verbose_name='处理说明')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='申请时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_requests_processed', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_requests', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '账号请求',
                'verbose_name_plural': '账号请求',
                'ordering': ('-requested_at', '-pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'request_type'), name='one_pending_account_request_per_type')],
            },
        ),
        migrations.CreateModel(
            name='MembershipChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(choices=[('L0', '待验证'), ('L1', '普通会员'), ('L2', '高级会员'), ('L3', '站长')], max_length=2, verbose_name='原等级')),
                ('to_level', models.CharField(choices=[('L0', '待验证'), ('L1', '普通会员'), ('L2', '高级会员'), ('L3', '站长')], max_length=2, verbose_name='新等级')),
                ('reason', models.CharField(max_length=240, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_changes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员等级变更',
                'verbose_name_plural': '会员等级变更',
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('from_level', models.F('to_level')), _negated=True), name='membership_change_requires_different_levels')],
            },
        ),
    ]
