# Generated by Django 5.2.17 on 2026-08-16 17:58

import datetime
import django.core.validators
import django.db.models.deletion
import publishing.documents.schema
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('article', '文章'), ('project', '项目'), ('note', '随记'), ('tool', '工具')], db_index=True, max_length=12, verbose_name='内容类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, verbose_name='网址标识')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name='首页推荐')),
                ('body_json', models.JSONField(default=publishing.documents.schema.empty_document, verbose_name='编辑正文 JSON')),
                ('rendered_html', models.TextField(blank=True, verbose_name='编辑正文 HTML')),
                ('body_text', models.TextField(blank=True, verbose_name='编辑正文纯文本')),
                ('published_body_json', models.JSONField(blank=True, null=True, verbose_name='线上正文 JSON')),
                ('published_rendered_html', models.TextField(blank=True, verbose_name='线上正文 HTML')),
                ('published_body_text', models.TextField(blank=True, verbose_name='线上正文纯文本')),
                ('published_title', models.CharField(blank=True, max_length=200, verbose_name='线上标题')),
                ('published_slug', models.SlugField(allow_unicode=True, blank=True, max_length=160, verbose_name='线上网址标识')),
                ('published_summary', models.CharField(blank=True, max_length=500, verbose_name='线上摘要')),
                ('published_featured', models.BooleanField(default=False, verbose_name='线上首页推荐')),
                ('published_metadata', models.JSONField(blank=True, default=dict, verbose_name='线上类型资料')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], db_index=True, default='draft', max_length=12, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='首次发布时间')),
                ('version', models.PositiveBigIntegerField(default=0, verbose_name='编辑版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='移入回收站时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishing_content_authored', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publishing_content_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
            ],
            options={
                'verbose_name': '内容',
                'verbose_name_plural': '内容',
                'ordering': ('-updated_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', '图片'), ('attachment', '普通附件')], max_length=12, verbose_name='类型')),
                ('file', models.FileField(max_length=500, upload_to='assets/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='素材名称')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='替代文字')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME 类型')),
                ('byte_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='移入回收站时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishing_assets_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True, verbose_name='标识')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='说明')),
                ('accent', models.CharField(default='#C8623A', max_length=7, validators=[django.core.validators.RegexValidator(message='颜色必须是六位十六进制值，例如 #C8623A。', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='标记颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('contententry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publishing.contententry')),
                ('published_on', models.DateField(default=datetime.date.today, verbose_name='文章日期')),
                ('reading_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='阅读分钟（人工覆盖）')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
            bases=('publishing.contententry',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('contententry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publishing.contententry')),
                ('project_status', models.CharField(choices=[('active', '进行中'), ('complete', '已完成'), ('maintained', '持续维护'), ('archived', '已归档')], default='active', max_length=12, verbose_name='项目状态')),
                ('started_on', models.DateField(default=datetime.date.today, verbose_name='开始日期')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='完成日期')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
            bases=('publishing.contententry',),
        ),
        migrations.AddField(
            model_name='contententry',
            name='cover_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_entries_as_cover', to='publishing.asset', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='contententry',
            name='published_cover_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_entries_as_published_cover', to='publishing.asset', verbose_name='线上封面'),
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(verbose_name='版本号')),
                ('action', models.CharField(choices=[('save', '手工保存前'), ('publish', '发布前'), ('restore', '恢复前'), ('unpublish', '取消发布前'), ('delete', '移入回收站前'), ('trash_restore', '移出回收站前')], max_length=16, verbose_name='动作')),
                ('snapshot', models.JSONField(verbose_name='版本快照')),
                ('summary', models.CharField(blank=True, max_length=240, verbose_name='修改摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='publishing.contententry', verbose_name='内容')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publishing_revisions_created', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '内容版本',
                'verbose_name_plural': '内容版本',
                'ordering': ('-number', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('site_name', models.CharField(default='少惰主 · SDZJOY', max_length=120, verbose_name='网站名称')),
                ('tagline', models.CharField(blank=True, max_length=240, verbose_name='网站简介')),
                ('owner_name', models.CharField(default='少惰主', max_length=80, verbose_name='站长称呼')),
                ('article_intro', models.CharField(blank=True, max_length=240, verbose_name='文章栏目说明')),
                ('project_intro', models.CharField(blank=True, max_length=240, verbose_name='项目栏目说明')),
                ('note_intro', models.CharField(blank=True, max_length=240, verbose_name='随记栏目说明')),
                ('tool_intro', models.CharField(blank=True, max_length=240, verbose_name='工具栏目说明')),
                ('about_intro', models.CharField(blank=True, max_length=280, verbose_name='关于页简介')),
                ('about_body_json', models.JSONField(default=publishing.documents.schema.empty_document, verbose_name='关于页正文 JSON')),
                ('about_rendered_html', models.TextField(blank=True, verbose_name='关于页正文 HTML')),
                ('about_body_text', models.TextField(blank=True, verbose_name='关于页纯文本')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('default_cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_profiles_as_default_cover', to='publishing.asset', verbose_name='默认封面')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.AddField(
            model_name='contententry',
            name='published_topics',
            field=models.ManyToManyField(blank=True, related_name='published_content_entries', to='publishing.topic', verbose_name='线上主题'),
        ),
        migrations.AddField(
            model_name='contententry',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='content_entries', to='publishing.topic'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('contententry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publishing.contententry')),
                ('noted_on', models.DateField(default=datetime.date.today, verbose_name='记录日期')),
                ('promoted_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_notes', to='publishing.article', verbose_name='整理后的文章')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='publishing.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '随记',
                'verbose_name_plural': '随记',
            },
            bases=('publishing.contententry',),
        ),
        migrations.AddField(
            model_name='article',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='publishing.project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('contententry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publishing.contententry')),
                ('launched_on', models.DateField(default=datetime.date.today, verbose_name='上线日期')),
                ('tool_status', models.CharField(choices=[('online', '在线'), ('beta', '测试中'), ('maintenance', '维护中'), ('retired', '已下线')], default='online', max_length=16, verbose_name='工具状态')),
                ('service_url', models.URLField(blank=True, max_length=1000, verbose_name='工具地址')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='源代码地址')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='publishing.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
            },
            bases=('publishing.contententry',),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 0)), name='publishing_asset_non_negative_size'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('content', 'number'), name='publishing_unique_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='publishing_revision_positive_number'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('save', 'publish', 'restore', 'unpublish', 'delete', 'trash_restore'))), name='publishing_revision_valid_action'),
        ),
        migrations.AddConstraint(
            model_name='siteprofile',
            constraint=models.CheckConstraint(condition=models.Q(('singleton', True)), name='publishing_site_profile_is_singleton'),
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.UniqueConstraint(fields=('kind', 'slug'), name='publishing_unique_slug_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.UniqueConstraint(condition=models.Q(('published_slug', ''), _negated=True), fields=('kind', 'published_slug'), name='publishing_unique_published_slug_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 0)), name='publishing_content_non_negative_version'),
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('published_at__isnull', False), _connector='OR'), name='publishing_published_content_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('published_slug', ''), _negated=True), _connector='OR'), name='publishing_published_content_has_slug'),
        ),
    ]
