# Generated by Django 5.2.17 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="legacy_source_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="旧系统标识",
            ),
        ),
        migrations.AddField(
            model_name="contententry",
            name="legacy_source_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="旧系统标识",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="legacy_source_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="旧系统标识",
            ),
        ),
    ]
