# Generated by Django 5.2.17 on 2026-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='告警标识')),
                ('title', models.CharField(max_length=300, verbose_name='告警标题')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('high', '高'), ('medium', '中')], max_length=12, verbose_name='等级')),
                ('status', models.CharField(choices=[('open', '待处理'), ('recovered', '已恢复')], db_index=True, default='open', max_length=12, verbose_name='状态')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='首次出现')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最近出现')),
                ('recovered_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
            ],
            options={
                'verbose_name': '运行告警',
                'verbose_name_plural': '运行告警',
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='MonitorCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='检查项')),
                ('url', models.CharField(max_length=500, verbose_name='检查地址')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('high', '高'), ('medium', '中')], max_length=12, verbose_name='等级')),
                ('ok', models.BooleanField(verbose_name='正常')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='状态码')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时毫秒')),
                ('error_kind', models.CharField(blank=True, max_length=80, verbose_name='错误分类')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='检查时间')),
            ],
            options={
                'verbose_name': '关键路径检查',
                'verbose_name_plural': '关键路径检查',
                'ordering': ('-checked_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='任务名称')),
                ('last_started_at', models.DateTimeField(blank=True, null=True, verbose_name='最近开始')),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True, verbose_name='最近成功')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='最近错误')),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0, verbose_name='连续失败')),
            ],
            options={
                'verbose_name': '后台任务状态',
                'verbose_name_plural': '后台任务状态',
            },
        ),
    ]
