# Generated by Django 5.2.17 on 2026-08-15 09:20

import datetime
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(max_length=280, verbose_name='简介')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('markdown', 2), ('code', 6), ('image', 7), ('table', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': '小标题', 'max_length': 140, 'template': 'content/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'label': '富文本'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': '原始 HTML 会被禁用并在输出时再次净化。', 'label': 'Markdown', 'template': 'content/blocks/markdown_block.html'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', '纯文本'), ('bash', 'Shell / Bash'), ('powershell', 'PowerShell'), ('python', 'Python'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('yaml', 'YAML'), ('nginx', 'Nginx')], 'label': '语言'}), 4: ('wagtail.blocks.TextBlock', (), {'label': '代码'}), 5: ('wagtail.blocks.CharBlock', (), {'label': '说明', 'max_length': 160, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4), ('caption', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '图片', 'template': 'content/blocks/image_block.html'}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格', 'table_options': {'colHeaders': False, 'editor': 'text', 'height': 216, 'minSpareRows': 0, 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'}})}, verbose_name='正文')),
            ],
            options={
                'verbose_name': '关于',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=240, verbose_name='栏目说明')),
            ],
            options={
                'verbose_name': '文章栏目',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoteIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=240, verbose_name='栏目说明')),
            ],
            options={
                'verbose_name': '随记栏目',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=240, verbose_name='栏目说明')),
            ],
            options={
                'verbose_name': '项目栏目',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(max_length=280, verbose_name='摘要')),
                ('status', models.CharField(choices=[('active', '进行中'), ('complete', '已完成'), ('maintained', '持续维护'), ('archived', '已归档')], default='active', max_length=12, verbose_name='状态')),
                ('started_on', models.DateField(default=datetime.date.today, verbose_name='开始日期')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('markdown', 2), ('code', 6), ('image', 7), ('table', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': '小标题', 'max_length': 140, 'template': 'content/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'label': '富文本'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': '原始 HTML 会被禁用并在输出时再次净化。', 'label': 'Markdown', 'template': 'content/blocks/markdown_block.html'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', '纯文本'), ('bash', 'Shell / Bash'), ('powershell', 'PowerShell'), ('python', 'Python'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('yaml', 'YAML'), ('nginx', 'Nginx')], 'label': '语言'}), 4: ('wagtail.blocks.TextBlock', (), {'label': '代码'}), 5: ('wagtail.blocks.CharBlock', (), {'label': '说明', 'max_length': 160, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4), ('caption', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '图片', 'template': 'content/blocks/image_block.html'}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格', 'table_options': {'colHeaders': False, 'editor': 'text', 'height': 216, 'minSpareRows': 0, 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'}})}, verbose_name='正文')),
            ],
            options={
                'verbose_name': '项目',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ToolIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=240, verbose_name='栏目说明')),
            ],
            options={
                'verbose_name': '工具栏目',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='标识')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='说明')),
                ('accent', models.CharField(default='#52d5c3', max_length=7, verbose_name='标记颜色')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(max_length=280, verbose_name='摘要')),
                ('published_on', models.DateField(default=datetime.date.today, verbose_name='文章日期')),
                ('reading_minutes', models.PositiveSmallIntegerField(default=8, verbose_name='预计阅读分钟')),
                ('featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('markdown', 2), ('code', 6), ('image', 7), ('table', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': '小标题', 'max_length': 140, 'template': 'content/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'label': '富文本'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': '原始 HTML 会被禁用并在输出时再次净化。', 'label': 'Markdown', 'template': 'content/blocks/markdown_block.html'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', '纯文本'), ('bash', 'Shell / Bash'), ('powershell', 'PowerShell'), ('python', 'Python'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('yaml', 'YAML'), ('nginx', 'Nginx')], 'label': '语言'}), 4: ('wagtail.blocks.TextBlock', (), {'label': '代码'}), 5: ('wagtail.blocks.CharBlock', (), {'label': '说明', 'max_length': 160, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4), ('caption', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '图片', 'template': 'content/blocks/image_block.html'}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格', 'table_options': {'colHeaders': False, 'editor': 'text', 'height': 216, 'minSpareRows': 0, 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'}})}, verbose_name='正文')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_pages', to='content.projectpage', verbose_name='所属项目')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, to='content.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '文章',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ToolPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(max_length=280, verbose_name='摘要')),
                ('launched_on', models.DateField(default=datetime.date.today, verbose_name='上线日期')),
                ('status', models.CharField(choices=[('online', '在线'), ('beta', '测试中'), ('maintenance', '维护中'), ('retired', '已下线')], default='online', max_length=16, verbose_name='状态')),
                ('service_url', models.URLField(blank=True, verbose_name='工具地址')),
                ('source_url', models.URLField(blank=True, verbose_name='源代码地址')),
                ('featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('markdown', 2), ('code', 6), ('image', 7), ('table', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': '小标题', 'max_length': 140, 'template': 'content/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'label': '富文本'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': '原始 HTML 会被禁用并在输出时再次净化。', 'label': 'Markdown', 'template': 'content/blocks/markdown_block.html'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', '纯文本'), ('bash', 'Shell / Bash'), ('powershell', 'PowerShell'), ('python', 'Python'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('yaml', 'YAML'), ('nginx', 'Nginx')], 'label': '语言'}), 4: ('wagtail.blocks.TextBlock', (), {'label': '代码'}), 5: ('wagtail.blocks.CharBlock', (), {'label': '说明', 'max_length': 160, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4), ('caption', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '图片', 'template': 'content/blocks/image_block.html'}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格', 'table_options': {'colHeaders': False, 'editor': 'text', 'height': 216, 'minSpareRows': 0, 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'}})}, verbose_name='正文')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_pages', to='content.projectpage', verbose_name='所属项目')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, to='content.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '工具',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='content.topic', verbose_name='主题'),
        ),
        migrations.CreateModel(
            name='NotePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(max_length=280, verbose_name='摘要')),
                ('noted_on', models.DateField(default=datetime.date.today, verbose_name='记录日期')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('markdown', 2), ('code', 6), ('image', 7), ('table', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': '小标题', 'max_length': 140, 'template': 'content/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'label': '富文本'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': '原始 HTML 会被禁用并在输出时再次净化。', 'label': 'Markdown', 'template': 'content/blocks/markdown_block.html'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', '纯文本'), ('bash', 'Shell / Bash'), ('powershell', 'PowerShell'), ('python', 'Python'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('yaml', 'YAML'), ('nginx', 'Nginx')], 'label': '语言'}), 4: ('wagtail.blocks.TextBlock', (), {'label': '代码'}), 5: ('wagtail.blocks.CharBlock', (), {'label': '说明', 'max_length': 160, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4), ('caption', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '图片', 'template': 'content/blocks/image_block.html'}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格', 'table_options': {'colHeaders': False, 'editor': 'text', 'height': 216, 'minSpareRows': 0, 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'}})}, verbose_name='正文')),
                ('promoted_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_notes', to='content.articlepage', verbose_name='整理后的文章')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_pages', to='content.projectpage', verbose_name='所属项目')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, to='content.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '随记',
            },
            bases=('wagtailcore.page',),
        ),
    ]
