# Generated by Django 5.2.17 on 2026-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('standard_changed', '标准信息变更'), ('standard_status_changed', '标准状态变更'), ('standard_added', '新增标准')], max_length=32, verbose_name='事件类型')),
                ('title', models.CharField(max_length=300, verbose_name='事件标题')),
                ('payload', models.JSONField(default=dict, verbose_name='事件数据')),
                ('dedupe_key', models.CharField(max_length=200, unique=True, verbose_name='去重标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='产生时间')),
            ],
            options={
                'verbose_name': '站内事件',
                'verbose_name_plural': '站内事件',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
