# Generated by Django 5.2.17 on 2026-08-15 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('standards', '0003_monitoringsource_candidatechange_candidatereview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='materialized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生成用户通知时间'),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('immediate', '即时'), ('digest', '周报')], default='immediate', max_length=12, verbose_name='通知节奏'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('standard_changed', '标准信息变更'), ('standard_status_changed', '标准状态变更'), ('standard_added', '新增标准'), ('resource_important', '重要资源变化'), ('content_published', '内容发布'), ('membership_changed', '会员等级变化'), ('security', '账号安全')], max_length=32, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('immediate', '即时通知'), ('weekly', '每周摘要')], max_length=12, verbose_name='邮件类型')),
                ('category', models.CharField(max_length=32, verbose_name='偏好类别')),
                ('subject', models.CharField(max_length=300, verbose_name='主题')),
                ('body', models.TextField(verbose_name='正文')),
                ('idempotency_key', models.CharField(max_length=240, unique=True, verbose_name='幂等标识')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('retry', '等待重试'), ('sent', '已发送'), ('skipped', '已取消'), ('failed', '发送失败')], db_index=True, default='pending', max_length=12, verbose_name='状态')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='尝试次数')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='下次尝试')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='最近错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='notifications.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '邮件投递',
                'verbose_name_plural': '邮件投递',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='接收邮件')),
                ('immediate_standard', models.BooleanField(default=True, verbose_name='重要规范变化')),
                ('immediate_resource', models.BooleanField(default=True, verbose_name='重要资源变化')),
                ('membership', models.BooleanField(default=True, verbose_name='会员等级变化')),
                ('weekly_digest', models.BooleanField(default=True, verbose_name='每周内容摘要')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知偏好',
                'verbose_name_plural': '通知偏好',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('project', '项目'), ('article', '文章'), ('note', '随记'), ('standard', '规范'), ('resource', '资源'), ('tool', '工具')], max_length=16, verbose_name='内容类型')),
                ('object_id', models.CharField(max_length=64, verbose_name='对象标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('user', 'item_type', 'object_id'), name='unique_favorite_item')],
            },
        ),
        migrations.CreateModel(
            name='ItemSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('project', '项目'), ('article', '文章'), ('note', '随记'), ('standard', '规范'), ('resource', '资源'), ('tool', '工具')], max_length=16, verbose_name='内容类型')),
                ('object_id', models.CharField(max_length=64, verbose_name='对象标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '单项订阅',
                'verbose_name_plural': '单项订阅',
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('user', 'item_type', 'object_id'), name='unique_item_subscription')],
            },
        ),
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='standards.taxonomyterm', verbose_name='主题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '主题订阅',
                'verbose_name_plural': '主题订阅',
                'ordering': ('taxonomy__sort_order', 'taxonomy__name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'taxonomy'), name='unique_topic_subscription')],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('body', models.TextField(blank=True, max_length=2000, verbose_name='摘要')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='站内地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='通知时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_notification')],
            },
        ),
    ]
