# Generated by Django 5.2.17 on 2026-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_event_materialized_at_event_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='status',
            field=models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('retry', '等待重试'), ('sent', '已发送'), ('skipped', '已取消'), ('failed', '发送失败')], db_index=True, default='pending', max_length=12, verbose_name='状态'),
        ),
    ]
