# Generated by Django 5.2.17 on 2026-08-15 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0003_monitoringsource_candidatechange_candidatereview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=8, verbose_name='文件类型')),
                ('file_hash', models.CharField(max_length=64, verbose_name='文件摘要值')),
                ('state', models.CharField(choices=[('ready', '校验通过，待确认'), ('invalid', '存在错误'), ('confirmed', '已确认发布'), ('failed', '文件解析失败')], db_index=True, max_length=12, verbose_name='导入状态')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='数据行数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误行数')),
                ('error_message', models.CharField(blank=True, max_length=1000, verbose_name='文件错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预览时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_imports_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_imports_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资源批量导入',
                'verbose_name_plural': '资源批量导入',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='资源名称')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='网址标识')),
                ('summary', models.TextField(max_length=5000, verbose_name='简介')),
                ('screenshot', models.ImageField(blank=True, upload_to='resources/screenshots/%Y/%m/', verbose_name='预览图')),
                ('screenshot_alt', models.CharField(blank=True, max_length=200, verbose_name='预览图说明')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='作者或制作人')),
                ('source_name', models.CharField(blank=True, max_length=300, verbose_name='来源名称')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='来源网址')),
                ('file_format', models.CharField(blank=True, max_length=120, verbose_name='主要格式')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='大小（字节）')),
                ('checksum_algorithm', models.CharField(blank=True, max_length=20, verbose_name='校验算法')),
                ('checksum_value', models.CharField(blank=True, max_length=256, verbose_name='校验值')),
                ('copyright_status', models.CharField(choices=[('self_made', '自制'), ('open_source', '开源许可'), ('official_free', '官方免费'), ('authorized', '已获授权'), ('metadata_only', '仅目录与合法来源'), ('restricted', '受版权限制'), ('unknown', '尚待确认')], db_index=True, default='unknown', max_length=20, verbose_name='版权状态')),
                ('copyright_note', models.TextField(blank=True, max_length=2000, verbose_name='版权与使用说明')),
                ('access_level', models.CharField(choices=[('L0', '公开区'), ('L1', '普通会员区'), ('L2', '高级会员区'), ('L3', '站长私人区')], db_index=True, default='L0', max_length=2, verbose_name='访问等级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=12, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_books', models.ManyToManyField(blank=True, related_name='related_resources', to='standards.referencebook', verbose_name='相关参考书')),
                ('related_manuals', models.ManyToManyField(blank=True, related_name='related_resources', to='standards.manual', verbose_name='相关手册')),
                ('related_standards', models.ManyToManyField(blank=True, related_name='related_resources', to='standards.standard', verbose_name='相关标准')),
                ('taxonomies', models.ManyToManyField(blank=True, related_name='resources', to='standards.taxonomyterm', verbose_name='适用主题')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ResourceMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('baidu', '百度网盘'), ('aliyun', '阿里云盘'), ('115', '115 网盘'), ('pcloud', 'pCloud'), ('quark', '夸克网盘'), ('official', '官方或原站'), ('other', '其他')], max_length=16, verbose_name='网盘或入口')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='入口名称')),
                ('share_url', models.URLField(max_length=1500, verbose_name='分享链接')),
                ('extraction_code', models.CharField(blank=True, max_length=80, verbose_name='提取码')),
                ('status', models.CharField(choices=[('active', '可用'), ('hidden', '已隐藏'), ('failed', '已失效'), ('replaced', '已更换')], db_index=True, default='active', max_length=12, verbose_name='入口状态')),
                ('failure_note', models.CharField(blank=True, max_length=500, verbose_name='失效或隐藏说明')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最后验证时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_mirrors_verified', to=settings.AUTH_USER_MODEL, verbose_name='最后验证人')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='resources.resourcemirror', verbose_name='替换入口')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrors', to='resources.resource', verbose_name='资源')),
            ],
            options={
                'verbose_name': '资源网盘入口',
                'verbose_name_plural': '资源网盘入口',
                'ordering': ('provider', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ResourceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('unavailable', '入口失效'), ('wrong_code', '提取码错误'), ('wrong_metadata', '信息有误'), ('copyright', '版权问题'), ('other', '其他')], max_length=20, verbose_name='问题类型')),
                ('details', models.TextField(blank=True, max_length=1500, verbose_name='问题说明')),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已处理'), ('rejected', '不成立')], db_index=True, default='open', max_length=12, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_note', models.CharField(blank=True, max_length=1000, verbose_name='处理说明')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_issues', to=settings.AUTH_USER_MODEL, verbose_name='反馈人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_issues_resolved', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='resources.resource', verbose_name='资源')),
                ('mirror', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='resources.resourcemirror', verbose_name='相关入口')),
            ],
            options={
                'verbose_name': '资源失效或纠错反馈',
                'verbose_name_plural': '资源失效或纠错反馈',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='原文件行号')),
                ('raw_data', models.JSONField(default=dict, verbose_name='原始行')),
                ('normalized_data', models.JSONField(default=dict, verbose_name='标准化预览')),
                ('errors', models.JSONField(default=list, verbose_name='校验错误')),
                ('state', models.CharField(choices=[('valid', '校验通过'), ('invalid', '存在错误'), ('imported', '已发布')], max_length=10, verbose_name='行状态')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='resources.importbatch', verbose_name='导入批次')),
                ('created_resource', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_row', to='resources.resource', verbose_name='已创建资源')),
            ],
            options={
                'verbose_name': '资源导入预览行',
                'verbose_name_plural': '资源导入预览行',
                'ordering': ('row_number',),
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_row_number_per_resource_import')],
            },
        ),
        migrations.CreateModel(
            name='ResourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=120, verbose_name='版本')),
                ('released_on', models.DateField(blank=True, null=True, verbose_name='版本日期')),
                ('change_notes', models.TextField(blank=True, max_length=3000, verbose_name='版本说明')),
                ('filename', models.CharField(blank=True, max_length=300, verbose_name='文件名')),
                ('file_format', models.CharField(blank=True, max_length=120, verbose_name='格式')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='大小（字节）')),
                ('checksum_algorithm', models.CharField(blank=True, max_length=20, verbose_name='校验算法')),
                ('checksum_value', models.CharField(blank=True, max_length=256, verbose_name='校验值')),
                ('is_current', models.BooleanField(default=True, verbose_name='当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resources.resource', verbose_name='资源')),
            ],
            options={
                'verbose_name': '资源版本',
                'verbose_name_plural': '资源版本',
                'ordering': ('-is_current', '-released_on', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('resource', 'version'), name='unique_version_per_resource'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('resource',), name='one_current_version_per_resource')],
            },
        ),
    ]
