# Generated by Django 5.2.17 on 2026-08-15 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_create_section_pages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='机构名称')),
                ('short_name', models.CharField(blank=True, max_length=80, verbose_name='简称')),
                ('official_url', models.URLField(blank=True, verbose_name='官方网站')),
            ],
            options={
                'verbose_name': '标准相关机构',
                'verbose_name_plural': '标准相关机构',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='标准编号')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='网址标识')),
                ('title_cn', models.CharField(max_length=300, verbose_name='中文名称')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='英文名称')),
                ('jurisdiction', models.CharField(choices=[('domestic', '国内设计依据'), ('foreign', '国外技术参考')], db_index=True, default='domestic', max_length=12, verbose_name='依据定位')),
                ('category', models.CharField(choices=[('national', '国家标准'), ('industry', '行业标准'), ('local', '地方标准'), ('group', '团体标准'), ('international', '国际标准'), ('foreign', '外国标准'), ('other', '其他')], db_index=True, max_length=16, verbose_name='标准类别')),
                ('nature', models.CharField(choices=[('mandatory', '强制性'), ('recommended', '推荐性'), ('guidance', '指导性文件'), ('unknown', '未标明')], default='unknown', max_length=16, verbose_name='标准性质')),
                ('status', models.CharField(choices=[('draft', '草案/未发布'), ('upcoming', '即将实施'), ('current', '现行'), ('withdrawn', '废止'), ('superseded', '被替代')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('use_level', models.CharField(choices=[('required', '必须采用'), ('related', '关联采用'), ('reference', '参考使用'), ('scenario', '特定场景使用')], default='reference', max_length=16, verbose_name='使用说明')),
                ('country_region', models.CharField(default='中国', max_length=100, verbose_name='国家或地区')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('effective_on', models.DateField(blank=True, null=True, verbose_name='实施日期')),
                ('withdrawn_on', models.DateField(blank=True, null=True, verbose_name='废止日期')),
                ('ics_code', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ICS 分类号')),
                ('ccs_code', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='CCS 分类号')),
                ('summary', models.TextField(blank=True, max_length=3000, verbose_name='适用范围与摘要')),
                ('author_note', models.TextField(blank=True, max_length=5000, verbose_name='少惰主备注')),
                ('verification_state', models.CharField(choices=[('unverified', '未核验'), ('verified', '已核验'), ('needs_review', '需要复核')], db_index=True, default='unverified', max_length=16, verbose_name='核验状态')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最后人工核验时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='related_standards', to='content.articlepage', verbose_name='相关文章')),
                ('related_tools', models.ManyToManyField(blank=True, related_name='related_standards', to='content.toolpage', verbose_name='相关工具')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standards_verified', to=settings.AUTH_USER_MODEL, verbose_name='最后核验人')),
            ],
            options={
                'verbose_name': '标准',
                'verbose_name_plural': '标准',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='SourceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('official_page', '官方信息页'), ('official_bulletin', '官方公告'), ('official_catalog', '官方目录'), ('legal_reference', '合法辅助来源')], max_length=20, verbose_name='来源类型')),
                ('title', models.CharField(max_length=300, verbose_name='证据标题')),
                ('url', models.URLField(max_length=1000, verbose_name='来源网址')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='发布机构')),
                ('excerpt', models.TextField(blank=True, max_length=2000, verbose_name='证据摘要')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='内容摘要值')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要证据')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='人工核验时间')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_evidence_verified', to=settings.AUTH_USER_MODEL, verbose_name='核验人')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='standards.standard', verbose_name='标准')),
            ],
            options={
                'verbose_name': '标准来源证据',
                'verbose_name_plural': '标准来源证据',
                'ordering': ('-is_primary', '-captured_at'),
            },
        ),
        migrations.CreateModel(
            name='StandardOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('issuer', '发布部门'), ('jurisdiction', '归口单位'), ('supervisor', '主管部门'), ('chief_editor', '主编单位'), ('participant', '参编单位')], max_length=20, verbose_name='机构角色')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='standards.organization')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards.standard')),
            ],
            options={
                'verbose_name': '标准编制机构',
                'verbose_name_plural': '标准编制机构',
                'ordering': ('role', 'organization__name'),
            },
        ),
        migrations.AddField(
            model_name='standard',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='standards', through='standards.StandardOrganization', to='standards.organization'),
        ),
        migrations.CreateModel(
            name='StandardRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('supersedes', '代替'), ('related', '相关标准')], max_length=16, verbose_name='关系')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='关系说明')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='standards.standard', verbose_name='当前标准')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='standards.standard', verbose_name='关联标准')),
            ],
            options={
                'verbose_name': '标准关系',
                'verbose_name_plural': '标准关系',
                'ordering': ('source__code', 'relation_type', 'target__code'),
            },
        ),
        migrations.CreateModel(
            name='StandardStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', '草案/未发布'), ('upcoming', '即将实施'), ('current', '现行'), ('withdrawn', '废止'), ('superseded', '被替代')], max_length=16, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('draft', '草案/未发布'), ('upcoming', '即将实施'), ('current', '现行'), ('withdrawn', '废止'), ('superseded', '被替代')], max_length=16, verbose_name='新状态')),
                ('effective_on', models.DateField(blank=True, null=True, verbose_name='本次状态生效日期')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='说明')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='standards.sourceevidence', verbose_name='依据证据')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='standards.standard', verbose_name='标准')),
            ],
            options={
                'verbose_name': '标准状态历史',
                'verbose_name_plural': '标准状态历史',
                'ordering': ('-changed_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('system', '数据中心系统'), ('topic', '专业主题'), ('design_stage', '设计阶段'), ('use_case', '使用性质')], max_length=20, verbose_name='分类维度')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('slug', models.SlugField(max_length=100, verbose_name='标识')),
                ('description', models.CharField(blank=True, max_length=280, verbose_name='说明')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='排序')),
            ],
            options={
                'verbose_name': '规范分类项',
                'verbose_name_plural': '规范分类项',
                'ordering': ('kind', 'sort_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='unique_standard_taxonomy_slug_per_kind')],
            },
        ),
        migrations.AddField(
            model_name='standard',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, related_name='standards', to='standards.taxonomyterm', verbose_name='专业分类'),
        ),
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='网址标识')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副标题')),
                ('authors', models.CharField(blank=True, max_length=400, verbose_name='作者或编者')),
                ('edition', models.CharField(blank=True, max_length=100, verbose_name='版次')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版社或发布机构')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ISBN')),
                ('summary', models.TextField(blank=True, max_length=3000, verbose_name='简介')),
                ('version_notes', models.TextField(blank=True, max_length=3000, verbose_name='版本说明')),
                ('official_url', models.URLField(blank=True, max_length=1000, verbose_name='官方或合法来源')),
                ('legal_source_note', models.CharField(blank=True, max_length=500, verbose_name='来源与版权说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('translators', models.CharField(blank=True, max_length=300, verbose_name='译者')),
                ('related_standards', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_items', to='standards.standard', verbose_name='相关标准')),
                ('taxonomies', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_items', to='standards.taxonomyterm', verbose_name='适用主题')),
            ],
            options={
                'verbose_name': '参考书',
                'verbose_name_plural': '参考书',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='网址标识')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副标题')),
                ('authors', models.CharField(blank=True, max_length=400, verbose_name='作者或编者')),
                ('edition', models.CharField(blank=True, max_length=100, verbose_name='版次')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版社或发布机构')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ISBN')),
                ('summary', models.TextField(blank=True, max_length=3000, verbose_name='简介')),
                ('version_notes', models.TextField(blank=True, max_length=3000, verbose_name='版本说明')),
                ('official_url', models.URLField(blank=True, max_length=1000, verbose_name='官方或合法来源')),
                ('legal_source_note', models.CharField(blank=True, max_length=500, verbose_name='来源与版权说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('series', models.CharField(blank=True, max_length=200, verbose_name='系列或丛书')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='编制机构')),
                ('related_standards', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_items', to='standards.standard', verbose_name='相关标准')),
                ('taxonomies', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_items', to='standards.taxonomyterm', verbose_name='适用主题')),
            ],
            options={
                'verbose_name': '技术手册',
                'verbose_name_plural': '技术手册',
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='standardorganization',
            constraint=models.UniqueConstraint(fields=('standard', 'organization', 'role'), name='unique_organization_role_per_standard'),
        ),
        migrations.AddConstraint(
            model_name='standardrelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='unique_relation_between_standards'),
        ),
        migrations.AddConstraint(
            model_name='standardrelation',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='standard_relation_cannot_reference_itself'),
        ),
        migrations.AddConstraint(
            model_name='standardstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='standard_status_history_requires_change'),
        ),
    ]
