# Generated by Django 5.2.17 on 2026-08-15 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_seed_taxonomies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='来源名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='来源标识')),
                ('source_url', models.URLField(max_length=1000, verbose_name='官方公告或目录地址')),
                ('feed_format', models.CharField(choices=[('manual_only', '仅手工创建候选'), ('sdzjoy_json', '受控 JSON 增量清单')], default='manual_only', max_length=20, verbose_name='检查方式')),
                ('enabled', models.BooleanField(db_index=True, default=False, verbose_name='启用定时检查')),
                ('automated_access_allowed', models.BooleanField(default=False, verbose_name='已确认允许自动访问')),
                ('access_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='访问规则复核时间')),
                ('access_review_note', models.CharField(blank=True, max_length=500, verbose_name='访问规则说明')),
                ('interval_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(30)], verbose_name='检查间隔（天）')),
                ('request_delay_seconds', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单次请求间隔（秒）')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(3)], verbose_name='请求超时（秒）')),
                ('max_response_bytes', models.PositiveIntegerField(default=1048576, validators=[django.core.validators.MinValueValidator(1024)], verbose_name='最大响应字节数')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='上次检查时间')),
                ('next_check_at', models.DateTimeField(blank=True, null=True, verbose_name='下次允许检查时间')),
                ('next_allowed_at', models.DateTimeField(blank=True, null=True, verbose_name='退避截止时间')),
                ('etag', models.CharField(blank=True, max_length=300, verbose_name='ETag 缓存')),
                ('last_modified', models.CharField(blank=True, max_length=300, verbose_name='Last-Modified 缓存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '规范检查来源',
                'verbose_name_plural': '规范检查来源',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CandidateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=200, verbose_name='来源条目标识')),
                ('fingerprint', models.CharField(blank=True, max_length=64, verbose_name='候选幂等摘要')),
                ('change_type', models.CharField(choices=[('new_standard', '新增标准'), ('status', '状态或日期变化'), ('metadata', '基础信息变化')], max_length=20, verbose_name='变化类型')),
                ('proposed_data', models.JSONField(default=dict, verbose_name='建议数据')),
                ('differences', models.JSONField(default=dict, verbose_name='差异摘要')),
                ('evidence_title', models.CharField(max_length=300, verbose_name='证据标题')),
                ('evidence_url', models.URLField(max_length=1000, verbose_name='证据网址')),
                ('state', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=12, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_changes', to='standards.standard', verbose_name='对应标准')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='standards.monitoringsource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '规范候选变更',
                'verbose_name_plural': '规范候选变更',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CandidateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', '通过'), ('reject', '拒绝')], max_length=8, verbose_name='审核决定')),
                ('note', models.CharField(blank=True, max_length=1000, verbose_name='审核说明')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='standards.candidatechange', verbose_name='候选变更')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_candidate_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('status_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_reviews', to='standards.standardstatushistory', verbose_name='产生的状态历史')),
            ],
            options={
                'verbose_name': '规范候选审核',
                'verbose_name_plural': '规范候选审核',
                'ordering': ('-reviewed_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CheckBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', '管理员手动'), ('scheduled', '月度计划')], max_length=12, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('running', '检查中'), ('completed', '发现候选'), ('no_change', '没有变化'), ('rate_limited', '来源限流'), ('failed', '检查失败')], db_index=True, default='running', max_length=16, verbose_name='批次状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('request_count', models.PositiveSmallIntegerField(default=0, verbose_name='请求次数')),
                ('candidate_count', models.PositiveIntegerField(default=0, verbose_name='新增候选数')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='结果说明')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='standards.monitoringsource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '规范检查批次',
                'verbose_name_plural': '规范检查批次',
                'ordering': ('-started_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000, verbose_name='本次来源地址')),
                ('response_status', models.PositiveSmallIntegerField(verbose_name='响应状态')),
                ('etag', models.CharField(blank=True, max_length=300, verbose_name='ETag')),
                ('last_modified', models.CharField(blank=True, max_length=300, verbose_name='Last-Modified')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='响应摘要值')),
                ('payload', models.JSONField(default=dict, verbose_name='受控增量数据')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='快照时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='standards.checkbatch', verbose_name='检查批次')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='standards.monitoringsource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '来源证据快照',
                'verbose_name_plural': '来源证据快照',
                'ordering': ('-captured_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='candidatechange',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='standards.sourcesnapshot', verbose_name='证据快照'),
        ),
        migrations.AddConstraint(
            model_name='checkbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('source',), name='one_running_check_batch_per_source'),
        ),
        migrations.AddConstraint(
            model_name='candidatechange',
            constraint=models.UniqueConstraint(fields=('source', 'fingerprint'), name='unique_candidate_fingerprint_per_source'),
        ),
    ]
